table AMZN
	lineageTag: b454b99f-b7d1-417a-a8d7-1bbb7c25359d

	column Date
		dataType: dateTime
		formatString: General Date
		lineageTag: 44e4b147-9ea3-4ca7-9f09-b452fe6ce062
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: ff754d2f-7512-4eac-b22a-931fd065ad11
			defaultHierarchy: LocalDateTable_44d7c61b-7136-4690-a2e1-ca9b646b4220.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Open
		dataType: double
		lineageTag: 97093154-3dc5-4963-931c-16ad11bdb22d
		summarizeBy: sum
		sourceColumn: Open

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column High
		dataType: double
		lineageTag: 1ad9ab3c-39af-41c5-a56d-3bb536b5e38b
		summarizeBy: sum
		sourceColumn: High

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Low
		dataType: double
		lineageTag: 87741c69-676d-4c48-b021-3cba6a377dfa
		summarizeBy: sum
		sourceColumn: Low

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Close
		dataType: double
		lineageTag: 9f5c8a0a-a44e-47da-b620-450c87f51709
		summarizeBy: sum
		sourceColumn: Close

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Volume
		dataType: int64
		formatString: 0
		lineageTag: f827af7d-0df9-42a3-b3de-baa71d8a36a6
		summarizeBy: sum
		sourceColumn: Volume

		annotation SummarizationSetBy = Automatic

	partition AMZN = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\Michael\Power BI Projects\PBITraining\AMZN.csv"),[Delimiter=",", Columns=6, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type datetime}, {"Open", type number}, {"High", type number}, {"Low", type number}, {"Close", type number}, {"Volume", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

